### ISSUE TITLE
iOS cannot upload random codes (build 64)

### ISSUE THREAD

**Issue by qanitah** [cds-snc/covid-alert-app#868] opened 2020-07-23 20:11 UTC
With all permissions on, entered a one time key and tried to up upload random codes. It says "Random codes could not be uploaded. you did not give permission". Deleted and reinstalled the app. Same thing.
Android 8 was fine.

iOS 13.5.1 on iPhone 7

![image](https://user-images.githubusercontent.com/14280062/88334060-30762f80-ccff-11ea-914b-1ac03c728bfb.png)

![image](https://user-images.githubusercontent.com/14280062/88333766-c3fb3080-ccfe-11ea-9c82-24f74a41b3b2.png)

**Comment by qanitah** [comment] 2020-07-24 13:17
Received notifications a couple of times in the evening to upload new random codes but was unable to since kept on getting same error "You did not give permission". All permissions were allowed.

iOS 13.5.1 on iPhone 7

![image](https://user-images.githubusercontent.com/14280062/88395004-5e568500-cd8e-11ea-8079-a04bd3ae1d59.png)


![image](https://user-images.githubusercontent.com/14280062/88395035-6a424700-cd8e-11ea-9b32-c8953c44f6a3.png)

**Comment by ndolter** [comment] 2020-07-24 14:39
This is also an issue on the Android 7 and IOS XR in ver 64.  Both of these devices had a positive diagnosis for days and when trying to upload and share the codes the message 'Random codes could not be uploaded - You did not give permission' was received.

**Comment by qanitah** [comment] 2020-07-27 17:27
Kept having the same issue for permission for days with versions 64 & 65 with iOS 13.5.1. 
Updated the iOS to 13.6 today and it worked.

**Comment by timarney** [comment] 2020-08-14 17:51
Closing this possibly was caused by modifying the database on the staging sever.

**Closed by timarney** 2020-08-14 17:51 UTC
