### ISSUE TITLE
BVC-90 :: Replace app snapshots with static image

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#411] opened 2020-07-04 14:24 UTC
Description

Both the iOS and Android versions of the app store "snapshots" on disk - these are screenshots taken of the app when a user minimizes the app, which in addition to remaining on disk, the OS will use as a preview of sorts in the app switcher.

Depending which screen the user was on before minimizing, the snapshot could potentially reveal if the user was diagnosed with COVID, or exposed to someone who was diagnosed. This may be a potential privacy concern.

Recommendation

Both operating systems offer a way to alter the app view before the app is minimized. This can be used to hide anything sensitive before the app is minimized and the OS takes a snapshot. The app already uses a static image as a loading splash screen - this image could be placed overtop the current app view so that it shows up as the snapshot.

Based on my research, on Android this can be done by altering the onPause() function to modify the view, before sending the app to the background. Similarly, on iOS this is done by altering the applicationDidEnterBackground() method in the AppDelegate. 

If the view is altered to display the static image, this image will then be used as a snapshot, ensuring no private app data is displayed. The image can then be removed from the view when the app is in the foreground again - using onResume() on Android and applicationWillEnterForeground() on iOS.

**Comment by obrien-j** [comment] 2020-07-04 14:24
dupe report from BBRY analysis as well, and also references to this in immuni and the corona-warn-app repo's.

I'm on the fence to be honest, so just marking for discussion to start.

**Comment by jeberhardt** [comment] 2020-07-07 12:41
This should be easy enough to implement. Here's a solution outlined, but it's only focused on iOS. Not sure if it would work for Android as well.

http://dbg.io/changing-your-preview-image-in-react-native-ios/

**Comment by jeberhardt** [comment] 2020-07-16 16:12
Using the typical approach for this issue, either on iOS or Android, the screen would be replaced when the app is in the background. In Android, this screen needs to be replaced with a blank, white screen.

The problem is that any time a system-based alert comes up, the app goes to the "background", even though the app is still visible behind the prompt. This means that there would be a white background behind the system prompt. 

I don't believe this is desireable, as it removes the user from the app, even though they are in the process of engaging with it.

![IMG_20200707_140105](https://user-images.githubusercontent.com/77435/87695531-9726a680-c75d-11ea-9f46-d8a1f758d89c.jpg)

**Comment by timarney** [comment] 2020-07-17 20:24
We need to discuss this at the UX level as it will impact the user flow.

**Comment by timarney** [comment] 2020-07-22 11:49
@amazingphilippe see https://github.com/cds-snc/covid-shield-mobile/issues/411#issuecomment-659515478

**Comment by henrytao-me** [comment] 2020-07-22 19:45
Confirm about what I did so that we don't have to do again. I have tried this as well as using `SplashScreen.show()` and `SplashScreen.hide()`. It doesn't work. The UI didn't change when the app is not in active state. So, we need to try native approach. 

```ts
interface SnapshotProtectionProps {
  children: React.ReactElement;
}

const SnapshotProtection = ({children}: SnapshotProtectionProps) => {
  const [isActive, setIsActive] = useState(true);
  useEffect(() => {
    const listener: (state: AppStateStatus) => void = state => {
      setIsActive(state === 'active');
    };
    AppState.addEventListener('change', listener);
    return () => {
      AppState.removeEventListener('change', listener);
    };
  }, []);
  return (
    <Box flex={1}>
      <Box flex={1}>{children}</Box>
      {!isActive && <Box backgroundColor="greenBackground" position="absolute" left={0} right={0} top={0} bottom={0} />}
    </Box>
  );
};
```

cc @jeberhardt @smcmurtry

**Comment by emilykuret** [comment] 2020-07-29 14:43
![](https://github.trello.services/images/mini-trello-icon.png) [App state should be hidden when running in the background](https://trello.com/c/0RlkCGw4/268-app-state-should-be-hidden-when-running-in-the-background)

**Comment by emilykuret** [comment] 2020-08-19 13:04
Item is in the backlog and will be merged in the coming weeks.

**Comment by timarney** [comment] 2020-10-19 20:37
No consensus was reached on this.

**Closed** 2020-10-19 20:40 UTC
Labels: CCCS, low priority, privsec
