### ISSUE TITLE
Remove "retrieve running apps" permission

### ISSUE THREAD

**Issue by fredvb** [cds-snc/covid-alert-app#1184] opened 2020-10-06 15:12 UTC
For some reason, this application requires "retrieve running apps" permissions.

This should be removed. If not, please explain why it can't be done.

**Comment by CalvinRodo** [comment] 2020-10-06 15:14
Duplicate of #979

**Closed by CalvinRodo** 2020-10-06 15:14 UTC
Labels: bug, inbox

**Comment by fredvb** [comment] 2020-10-06 15:20
Just noticed it. Thanks
