### ISSUE TITLE
Increase frequency of exposure recording

### ISSUE THREAD

**Issue by csavard-sudo** [cds-snc/covid-alert-app#1332] opened 2021-01-05 16:43 UTC
## Summary | Résumé

The threshold to record an exposure is exceptionally high. Even though I have had the app since launch, I have no way of knowing if my phone has ever recorded an exposure and doubt I have ever been in contact with someone for 15 minutes or longer within 2 metres. I suspect this is the case for many of those who have downloaded the app, as the type of person to have downloaded the app is probably the same one who practices the distancing and safety measures when out in public. 

----
# Design detail | Précisions au sujet de la conception

If someone has the app active and has had 0 (or near-zero) contacts, increase the sensitivity for recording contacts. Whether it's increasing to a 5 metre radius, decreasing the time period 5-10 minutes... anything to make the app of some use to them. It would also be useful to have a information that noted the amount of contacts that were recorded in the past 14 days.

**Comment by csavard-sudo** [comment] 2021-01-05 16:46
I have no idea why the first paragraph is header text. if someone can edit that to fix that feel free.

**Comment by CalvinRodo** [comment] 2021-01-07 00:02
Thanks for the issue, at the moment we have set app thresholds based on guidance from Public Health Authorities. 

I'm going to close this as we currently have no plans to change our thresholds, however we will re-open or reference this issue if that changes.

**Closed by CalvinRodo** 2021-01-07 00:02 UTC
Labels: enhancement, inbox

**Comment by csavard-sudo** [comment] 2021-01-07 00:29
Fine, I strongly disagree as other countries such as Germany have implemented [similar solutions](https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf) but I guess our tech/public health guidance will always lag behind that of leaders in the EU. 

With that said, that only addresses a part of the request. A box indicating the number of exposures you have recorded in the past 14 days would be useful. Is there any other way of knowing that this app is useful for people who practice physical distancing and the like without telling them "Hey, the app is working - we've recorded 6 contacts in the past 2 weeks". As I have previously said, the threshold for recording an exposure is extremely high so I doubt that those who actually follow physical distancing measures would record one. 

This app may only be useful for those who have to use public transit/trains/airplanes as I cannot imagine many of the type of people who download this app to otherwise be in situations where they aren't physically distancing for 15 minutes (let alone two of them in the same place!)

**Comment by CalvinRodo** [comment] 2021-01-07 00:38
Sorry about that, for the issue of number of exposures please open a separate issue so we can track them both separately


As for influencing public health guidelines I recommend you reach out to your local MP or public health authorities for that.

**Comment by LeCanardQuoi** [comment] 2021-01-07 15:14
Note that this has also been entered over three weeks ago under #1304 (and subsequently closed/deferred for internal team review). No problem reports updates have been made via this GIThub server tool. Better communications and more transparency remain sought, including active participation of the canadians council advisory board on several enhancement requests out of current "scope" schedule/budget.

**Comment by uhengart** [comment] 2021-01-08 03:09
Actually, @csavard-sudo raises an interesting point. Health Canada requires a maximum distance of 2m. But the app has no concept of distance. All it has is the attenuation of the received signal, i.e., how much weaker is the received signal than the transmitted signal. Determining an attenuation threshold that (reliably) satifies the 2m requirement is hard since attenuation is not only caused by distance; the environment and the device placement also affect it. The app seems to use a threshold of 63 dB (src/services/ExposureNotificationService/ExposureConfigurationDefault.json). Where is this threshold coming from? Health Canada?

**Comment by LeCanardQuoi** [comment] 2021-01-08 14:38
> Actually, @csavard-sudo raises an interesting point. Health Canada requires a maximum distance of 2m. But the app has no concept of distance. All it has is the attenuation of the received signal, i.e., how much weaker is the received signal than the transmitted signal. Determining an attenuation threshold that (reliably) satifies the 2m requirement is hard since attenuation is not only caused by distance; the environment and the device placement also affect it. The app seems to use a threshold of 63 dB (src/services/ExposureNotificationService/ExposureConfigurationDefault.json). Where is this threshold coming from? Health Canada?

Bluetooth was never designed to be used on a tight 2 meters spec. I believe that the ENS framework does provide for a 5 minutes proximity contact timer. Other countries using the ENS platform for their app have integrated support for QR code (and tokens) such as Singapore. Public indoor locations are more problematic for tracking proximity contacts and droplets transmission issues. So the existing app would need some repurposing and deal with diagnosed sites types of notifications and related tracking. See ER ...

**Comment by emilykuret** [comment] 2021-01-08 14:53
These parameters have been set in collaboration with Health Canada, Public Health Agency of Canada, as well as Apple and Google. We have also conducted research and collaborated with other countries on the implementation of this. We work with the Linux Foundation Public Health, and you can find some of their resources on Risk Scoring here: https://github.com/lfph/gaen-risk-scoring/blob/main/risk-scoring.md

**Comment by LeCanardQuoi** [comment] 2021-01-17 21:57
> These parameters have been set in collaboration with Health Canada, Public Health Agency of Canada, as well as Apple and Google. We have also conducted research and collaborated with other countries on the implementation of this. We work with the Linux Foundation Public Health, and you can find some of their resources on Risk Scoring here: https://github.com/lfph/gaen-risk-scoring/blob/main/risk-scoring.md

Note that the Google/Apple frameworks provides for shorter timers setting like 5 minutes. And the Risk Scoring initiative did not advise on the timer setting prior to the emergence of a more virulent strain: "The weights for the configurations above assume health authorities will prefer to use a threshold of 15 minutes (for ease of communication and consistency in messaging). While this parameter can also be adjusted, the group did not evaluate the impact of changing it." Is the ease of "Messaging" constraining the requirements???
