### ISSUE TITLE
Positively diagnosed devices w Bluetooth off not behaving the same in iOS vs Android version 47

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-alert-app#680] opened 2020-07-14 16:41 UTC
device 1: Android 8 - OnePlus 3
device 2: iPhone XR (13.5.1)
both have v47 COVID Alert
steps were done simultaneously on both devices. (July 13 around 220pm)

1. installed app 
2. entered a diagnosis code successfully and agreed to share random ids.
3. turned off Bluetooth (via Settings)

July 14 630am
both devices rec'd push notification for Upload your random ids.
clicked the notification on each device, app opens.
iOS: Bluetooth is off message appears 
   can't upload codes.
Android: Turn on notification prompt appears - Clicked Cancel.
   msg on home screen: Upload your random codes (Menu shows COVID Alert is off)
   Clicked Share codes - Agree then get Random codes could not be uploaded. clicked Ok then Cancel

expected behaviour should be somewhat similar.

**Comment by henrytao-me** [comment] 2020-07-23 12:58
Note: this is expected behavior.

## Explain: 
- On Android, the app combines bluetooth and EN permission. When EN permission is turned on, the OS automatically turns on bluetooth. 
- On iOS, the OS cannot do the same thing. That's why bluetooth is off message appears. 

Close as non issue. Please reopen if needed.

**Comment by mmiron-HC** [comment] 2020-07-27 10:54
@henrytao-me The app was installed, Exposure Notifications were turned on as part of the on boarding AND I had entered a valid diagnosis code, THEN I turned off Bluetooth. 
Please re-open.

**Comment by henrytao-me** [comment] 2020-07-27 11:44
@mmiron-HC Do you have a video how the bug looks like? 🙇

**Comment by mmiron-HC** [comment] 2020-07-28 11:11
@henrytao-me no, sorry.

**Comment by emilykuret** [comment] 2020-08-19 13:11
Moving this to another issue.

**Closed** 2020-08-19 13:11 UTC
Labels: tester
